name: 功能建议
description: 想增加或改进的功能。
body:
  - type: textarea
    id: idea
    attributes:
      label: 想增加或改进的功能
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: 使用场景或示例
    validations:
      required: false
